### ISSUE TITLE
Error message when I search a student

### ISSUE THREAD

**Issue by markxus23** [OS4ED/openSIS-Classic#140]
SQL:	SELECT CONCAT(s.LAST_NAME,', ',coalesce(s.COMMON_NAME,s.FIRST_NAME)) AS FULL_NAME,s.LAST_NAME,s.FIRST_NAME,s.MIDDLE_NAME,s.STUDENT_ID,s.PHONE,ssm.SCHOOL_ID,s.ALT_ID,ssm.SCHOOL_ID AS LIST_SCHOOL_ID,ssm.GRADE_ID ,ssm.SECTION_ID FROM students s ,student_enrollment ssm WHERE ssm.STUDENT_ID=s.STUDENT_ID AND ssm.SYEAR='2015' AND (ssm.START_DATE IS NOT NULL AND ('2020-10-02'<=ssm.END_DATE OR ssm.END_DATE IS NULL) OR ssm.DROP_CODE= ) AND ssm.SYEAR='2015' AND ssm.SCHOOL_ID='2' AND s.IS_DISABLE IS NULL AND LOWER(s.LAST_NAME) LIKE 'aldana%' ORDER BY FULL_NAME Traceback:	F:\xampp\htdocs\opensis-ce\functions\GetStuListFnc.php at 603 Additional Information:	You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND ssm.SYEAR='2015' AND ssm.SCHOOL_ID='2' AND s.IS_DISABLE IS NULL AND LO...' at line 1

**Comment by markxus23** [comment]
Please help.. don't know how to code to fix this issue. anyone please guide me to fix the issue. thanks a lot

**Comment by openSISAdmin** [comment]
Looks like you have copy pasted the new code instead of upgrading or installing a new version.

Please run this SQL:

ALTER TABLE `students` CHANGE `ethnicity` `ethnicity_id` INT(11) NULL DEFAULT NULL;

DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 13;
DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 14;
DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 12;
DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 15;

Let us know if this fixes your problem.

**Comment by markxus23** [comment]
Thanks a lot. I'll update you soon if this will work.

**Comment by openSISAdmin** [comment]
Could not replicate this error.
