### ISSUE TITLE
Print Catalog by Grade Level

### ISSUE THREAD

**Issue by klmartinson17** [OS4ED/openSIS-Classic#213]
Works only when "Select Grade Level: All" is selected.
I have Grade 6, 7, 8. If I select any of the grades, then the message "No Courses were found in this Grade Level" appears.

The menu item "Print all Courses" works.
The mentu item "Print Catalog by Term". The "Select Term" drop-down box has the items "All"  "Year title" and "Term 1", "Term 2" and "Term 3".  All work except for the "Year title" menu option which should not be there, since it is not a Term. The output is: "No Courses are found in this term"

**Comment by sayan-os4ed** [comment]
Hello,

We are unable to replicate the scenario for the "Print Catalog by Grade Level" menu. If you have a Course that is created by selecting a particular Grade Level and if Course Periods are available in that particular Course then the data should appear when you generate the report by selecting that particular Grade Level.

In the "Print Catalog by Term" menu, the "Term" refers to the available Marking Periods of the system, and the "Year title" is available in the option because a Course Period can be created by selecting the Full Year as the duration of the Course Period.

Thank you!

**Comment by klmartinson17** [comment]
My mistake. I did not restrict courses to a certain year.
